# Generated by Django 4.1.1 on 2022-11-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0005_profile_major_profile_schedule_profile_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
