# Generated by Django 4.1.1 on 2022-11-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0006_remove_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='schedule',
        ),
    ]
